### ISSUE TITLE
4.0.0 버전에서 동작 안함 :(

### ISSUE THREAD

**Issue by mzggr0914** [CmlLib/CmlLib.Core.Installer.Forge#4]
그리고 깃에 베타 버전좀 올려주세요.
빨리 4.0.0 이랑 호환되게 업데이트좀

**Comment by AlphaBs** [comment]
4.0.0 정식 릴리즈가 나오면 업데이트할 예정입니다. 아직 4.0.0 은 베타 버전이고 public API 가 언제든 바뀔 수 있어요.
